---
title: "Mini-Project 2"
author: "Carol, Lauren, Neamat"
date: "2019-03-24"
output: 
  html_document:
    code_folding: hide
---

## Data Graphic

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(wordcountaddin)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
# Lauren setting up the Contributions Table for the inner_join()

contributions_clean <- contributions %>%
  filter(transaction_type == "24A" | transaction_type == "24E") %>%
  filter(transaction_amt > 0) %>%
  spread(transaction_type, transaction_amt, fill = 0) %>%
  rename(against = "24A") %>%
  rename(support = "24E") %>%
  select(cand_id, against, support) %>%
  group_by(cand_id) %>%
  summarize(total_for = sum(support), total_against = sum(against))
```

```{r}
# Carol setting up the House Elections Table for the inner_join()

elections <- house_elections %>%
 filter(general_votes > 0, !is.na(fec_id)) %>%
  
 select(fec_id, incumbent, party, general_votes, ge_winner) %>%
  filter(general_votes > 0, !is.na(fec_id)) %>%
  select(fec_id, incumbent, party, general_votes, ge_winner) %>%
  rename(cand_id = fec_id) 

# Neamat added a rename function so joining would be easier
```

```{r}
# Neamat trying to inner_join() by candidate's ids

joined_plot <- inner_join(contributions_clean, elections,
                         by = "cand_id")
```

```{r, warning=FALSE}
# Neamat making it into a rough graph
# Everyone editing this rough graph into a final graph

incumbent_plot <- ggplot(joined_plot, aes(x =(total_for), y = general_votes, color = incumbent)) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_jitter() +
  scale_x_log10(name = "Total Contributions per Candidate") +
  scale_y_log10(name = "General Votes per Candidate",
                limits = c(3e+04, 3e+05)) +
  ggtitle("Effectiveness of Campaign Contributions",
          subtitle = "Between Incumbents and Challengers") +
  scale_color_discrete(name = "Incumbent") +
  facet_wrap(~incumbent)

incumbent_plot
```

```{r include=FALSE}
incumbents <- joined_plot %>%
  filter(incumbent == TRUE)

Inc_model <- lm(general_votes~total_for, data = incumbents)
summary(Inc_model)

challengers <- joined_plot %>%
  filter(incumbent == FALSE)

chall_model <- lm(general_votes ~ total_for, data = challengers)
summary(chall_model)
```

> Word count: `r wordcountaddin::word_count()`